stages:
  - test
  - deploy

node_testing:
  stage: test
  image: node:18
  tags:
    - dsa
    - DIND
  script:
    - git config --global --add safe.directory /builds/infor-design/ids-legacy
    - npm ci
    #- npm run build
    #- npm run lint
    - echo "$GITHUB_CONTEXT"
    - echo "$JOB_CONTEXT"

deploy_demo:
  stage: deploy
  image: docker:25
  variables:
    DOCKER_HOST: tcp://host:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:25-dind
      alias: host
  tags:
    - dsa
    - DIND
  script:
    - echo "branch=$(echo ${CI_COMMIT_REF_NAME})"
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
    - /bin/bash scripts/deploy-environment/utils.sh install_packages
    #- make_dockerfile
    - ls -al
    - ls -al /bin/
    - echo $CI_COMMIT_REF_NAME
