stages:
  - test
  - deploy

node_testing:
  stage: test
  image: sickcodes/docker-osx:latest
  script:
    - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
    - apt-get install -y nodejs
    - npm install -g npm@latest
    - npm ci
    - npm run build
    - npm run lint
    - (npm run quickstart &) && sleep 5; npm run test
    - echo "$GITHUB_CONTEXT"
    - echo "$JOB_CONTEXT"
  tags:
    - dsa
    - DIND

deploy_demo:
  stage: deploy
  script:
    - echo "branch=$(echo ${CI_COMMIT_REF_NAME})"
