stages:
  - test
  - deploy

node_testing:
  stage: test
  image: node:18
  tags:
    - dsa
    - DIND
  script:
    - git config --global --add safe.directory /builds/infor-design/ids-legacy
    - npm ci
    #- npm run build
    #- npm run lint
    - echo "$GITHUB_CONTEXT"
    - echo "$JOB_CONTEXT"

deploy_demo:
  stage: deploy
  tags:
    - dsa
    - DIND
  script:
    - echo "branch=$(echo ${CI_COMMIT_REF_NAME})"
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
    - docker buildx create --use
