stages:
  - build
  - test

test:
  tags:
    - dsa
    - DIND
  image: docker:25
  variables:
      DOCKER_HOST: tcp://host:2375/
      DOCKER_DRIVER: overlay2
      DOCKER_TLS_CERTDIR: ""
  stage: test
  script:
    - ls -al

build-push:
  tags:
    - dsa
    - DIND
  image: docker:25
  variables:
    DOCKER_HOST: tcp://host:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  stage: build
  script:
    - ls -al
    - pwd
    - echo $DOCKER_HOST
    - docker build .
  services:
    - name: docker:25-dind
      alias: host
