stages:
  - test
  - deploy

node_testing:
  stage: test
  image: node:18
  script:
    - npm ci
    - npm run build
    - npm run lint
    - echo "$GITHUB_CONTEXT"
    - echo "$JOB_CONTEXT"
  tags:
    - dsa
    - DIND

deploy_demo:
  stage: deploy
  script:
    - echo "branch=$(echo ${CI_COMMIT_REF_NAME})"
