/* eslint-disable no-underscore-dangle */
import csp from 'express-csp';
import express from 'express';

import session from 'express-session';
import mmm from 'mmm';
import * as path from 'path';
import { fileURLToPath } from 'url';
import crypto from 'crypto';

import requestLoggers from './src/js/middleware/request-logger.js';
import cmdParamsHandlers from './src/js/middleware/cmd-params-handler.js';
import optionHandlers from './src/js/middleware/option-handler.js';
import optionHandlerThemes from './src/js/middleware/option-handler-themes.js';
import optionHandlerFonts from './src/js/middleware/option-handler-fonts.js';
import basePathHandler from './src/js/middleware/basepath-handler.js';
import globalDataHandler from './src/js/middleware/global-data-handler.js';
import responseThrottler from './src/js/middleware/response-throttler.js';
import removeHeaders from './src/js/middleware/remove-headers.js';
// import cspHandler from './src/js/middleware/csp-handler.js';

import utils from './src/js/utils.js';
import getJSONFile from './src/js/get-json-file.js';

import customRoutes from './src/js/routes/custom-routes.js';
import generalRoute from './src/js/routes/general.js';
import sendGeneratedDocPage from './src/js/routes/docs.js';
import data from './src/js/routes/data.js';
import errorHandler from './src/js/middleware/error-handler.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();

const BASE_PATH = process.env.BASEPATH || '/';
const packageJSON = getJSONFile('../../../package.json');

// Used for serving folders that shouldn't be cached for development purposes.
const NO_ETAG = {
  etag: false
};

app.set('view engine', 'html');
app.set('views', path.resolve(__dirname, 'views'));
app.set('basepath', BASE_PATH);

mmm.setEngine('hogan.js');
app.engine('html', mmm.__express);

// Because you're the type of developer who cares about this sort of thing!
app.enable('strict routing');

// Serve static assets
app.use(express.static(path.resolve(__dirname, 'www'))); // non-generated
app.use('/ids-css', express.static(path.resolve(__dirname, '..', 'node_modules', 'ids-css', 'dist'))); // ids-css import

// Serve pre-generated assets
app.use('/docs', express.static(path.resolve(__dirname, 'docs'), NO_ETAG)); // generated by building documentation
app.use(express.static(path.resolve(__dirname, 'dist'), NO_ETAG)); // app's `/dist` folder (generated by build)
app.use(express.static(path.resolve(__dirname, '..', 'dist'), NO_ETAG)); // project-level `/dist` folder (generated by build)
app.use('/src', express.static(path.resolve(__dirname, '..', 'src'), NO_ETAG)); // project-level `/src` folder for correct SCSS sourcemap linking

const token = crypto.randomBytes(64).toString('hex');

app.use(session({
  secret: token,
  resave: false,
  saveUninitialized: false,
  cookie: {
    httpOnly: true,
    sameSite: 'lax',
    secure: false
  }
}));

// Create the express router with the same settings as the app.
const router = express.Router({
  strict: true
});

// ===========================================
// Default Options / Custom Middleware
// ===========================================
const DEFAULT_RESPONSE_OPTS = {
  enableLiveReload: true,
  layout: 'layout',
  locale: 'en-US',
  title: 'IDS Enterprise',
  headerHamburger: false,
  appMenuOpen: false,
  basepath: BASE_PATH,
  version: packageJSON.version,
  csp: true,
  nonce: null
};

// Add CSP headers
csp.extend(app);

// Import various custom middleware (order matters!)
app.use(requestLoggers(app));
app.use(cmdParamsHandlers(app, DEFAULT_RESPONSE_OPTS));
app.use(optionHandlers(app));
app.use(optionHandlerThemes(app));
app.use(optionHandlerFonts());
app.use(basePathHandler(app));
app.use(globalDataHandler(app));
app.use(responseThrottler(app));
app.use(removeHeaders(app));
// TODO
// app.use(cspHandler(app));

app.use(router);

// ======================================
//  Main Routing and Param Handling
// ======================================
router.get('/', (req, res) => {
  res.render('kitchen-sink', res.opts);
});

router.get('/index', (req, res, next) => {
  const opts = {
    path: path.resolve(__dirname, 'docs', 'index.html')
  };

  if (utils.hasFile(opts.path)) {
    sendGeneratedDocPage(opts, req, res, next);
  }

  res.render('kitchen-sink', res.opts);
});

router.get('/kitchen-sink', (req, res) => {
  res.render('kitchen-sink', res.opts);
});

// ======================================
//  Components Routes
// ======================================
app.use('/behaviors', generalRoute);
app.use('/components', customRoutes);
app.use('/components', generalRoute);
app.use('/examples', generalRoute);
app.use('/utils', generalRoute);

// =========================================
// Fake 'API' Calls for use with AJAX-ready Controls
// =========================================
app.use('/api', data);

// =========================================
// Catch-all 404 at the base router level
// =========================================
app.use((req, res, next) => {
  res.status(404);
  next(`File "${req.originalUrl}" was not found`);
});

// =========================================
// Error Handling
// =========================================
app.use(errorHandler(app));

export default app;
