(function (factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module
    define('cultures/en-US', ['jquery'], factory);
    factory();
  } else if (typeof exports === 'object') {
    // Node/CommonJS
    module.exports = factory(require('jquery'));
  } else {
    // Browser globals
    factory(jQuery);
  }
}(function () {

  if (!Locale) {
    return;
  }

  //Get Latest from http://www.unicode.org/Public/cldr/25/
  Locale.addCulture('en-US', {
    //layout/language
    language: 'en',
    englishName: 'English (United States)',
    nativeName: 'English (United States)',
    //layout/orientation/@characters
    direction: 'left-to-right',
    //ca-gregorian
    calendars: [{
      name: 'gregorian',
      //ca-gregorian/main/dates/calendars/gregorian/dateFormats/
      dateFormat: {'seperator': '/', //Infered
                   'short': 'M/d/yyyy', //use four digit year
                   'medium': 'MMM d, yyyy',
                   'long': 'MMMM d, yyyy',
                   'full': 'EEEE, MMMM d, y',
                   'datetime': 'M/d/yyyy h:mm a'}, //Infered short + short gregorian/dateTimeFormats
      //ca-gregorian/main/dates/calendars/gregorian/days/format/short or abbreviated (2 digit)
      days: {
         wide: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
         abbreviated: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa']
      },
      //ca-gregorian/main/dates/calendars/gregorian/months/format/wide
      months: {
        wide: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        abbreviated: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
      },
      //ca-gregorian/main/dates/calendars/gregorian/timeFormats/short
      timeFormat: 'h:mm a',
      //ca-gregorian/main/dates/calendars/gregorian/dayPeriods/wide
      dayPeriods: ['AM', 'PM']
    }],
    //numbers/currencyFormats-numberSystem-latn/standard (Replace Sign http://www.currencysymbols.in ?)
    currencySign: '$', //(Replace Sign http://www.currencysymbols.in ?)
    currencyFormat: '¤#,##0.00',
    //numbers/symbols-numberSystem-latn
    numbers: {
      percentSign: '%',
      minusSign: '-',
      decimal: '.',
      group: ','
    },
    //Resx - Approved By Translation Team
    messages: {
      'AboutText': {id: 'AboutText', value: 'Copyright &copy; {0} Infor. All rights reserved. The word and design marks set forth herein are trademarks and/or registered trademarks of Infor and/or its affiliates and subsidiaries. All rights reserved. All other trademarks listed herein are the property of their respective owners'},
      'Actions': {id: 'Actions', value: 'Actions', comment: 'Tooltip text for the action button with additional in context actions'},
      'Add': {id: 'Add', value: 'Add', comment: 'Add'},
      'AdvancedFilter': {id: 'AdvancedFilter', value: 'Create Advanced Filter', comment: 'In a data grid active an advanced filtering feature'},
      'Alert': {id: 'Alert', value: 'Alert', comment: 'Alert'},
      'AllResults': {id: 'AllResults', value: 'All Results For', comment: 'Search Results Text'},
      'AligntoBottom': {id: 'AligntoBottom', value: 'Align to Bottom', comment: 'Align to Bottom in icons tooltip title'},
      'AlignCenterHorizontally': {id: 'AlignCenterHorizontally', value: 'Align Center Horizontally', comment: 'Align Center Horizontally in icons tooltip title'},
      'Amber': {id: 'Amber', value: 'Amber', comment: 'Color in our color pallette'},
      'Amethyst': {id: 'Amethyst', value: 'Amethyst', comment: 'Color in our color pallette'},
      'Attach': {id: 'Attach', value: 'Attach', comment: 'Attach'},
      'Azure': {id: 'Azure', value: 'Azure', comment: 'Color in our color pallette'},
      'Between': {id: 'Between', value: 'Between', comment: 'Between in icons for filtering'},
      'Blockquote': {id: 'Blockquote', value: 'Block quote', comment: 'insert a block quote in the editor'},
      'Bold': {id: 'Bold', value: 'Bold', comment: 'Make text Bold'},
      'Bookmarked': {id: 'Bookmarked', value: 'Bookmarked', comment: 'Bookmark filled'},
      'BookmarkThis': {id: 'BookmarkThis', value: 'Bookmark This', comment: 'Bookmark outlined'},
      'Breadcrumb': {id: 'Breadcrumb', value: 'Breadcrumb', comment: 'Text describing the Breadcrumb'},
      'BulletList': {id: 'BulletList', value: 'Bullet List', comment: 'Bullet List in icons tooltip title'},
      'Calendar': {id: 'Calendar', value: 'Calendar', comment: 'Inline Text for the title of the Calendar control'},
      'Camera': {id: 'Camera', value: 'Camera', comment: 'Camera in icons tooltip title'},
      'Cancel': {id: 'Cancel', value: 'Cancel', comment: 'Cancel in icons tooltip title'},
      'CapsLock': {id: 'CapsLock', value: 'Caps Lock', comment: 'Caps Lock in icons tooltip title'},
      'CapsLockOn': {id: 'CapsLockOn', value: 'Caps Lock On', comment: 'Caps Lock On message'},
      'Cart': {id: 'Cart', value: 'Cart', comment: 'Cart in icons tooltip title'},
      'CenterText': {id: 'CenterText', value: 'Center Text', comment: 'Center Text in icons tooltip title'},
      'ChangeSelection': {id: 'ChangeSelection', value: '. To change the selection use the arrow keys.', comment: 'Audible Text for drop down list help'},
      'Checkbox': {id: 'Checkbox', value: 'Checkbox', comment: 'Checkbox in icons tooltip title'},
      'Checked': {id: 'Checked', value: 'Checked', comment: 'Checked in icons tooltip title'},
      'Clear': {id: 'Clear', value: 'Clear', comment: 'Hint for a Clear Action'},
      'Clock': {id: 'Clock', value: 'Clock', comment: 'Clock in icons tooltip title'},
      'Close': {id: 'Close', value: 'Close', comment: 'Hint for a Close Button Action'},
      'Copy': {id: 'Copy', value: 'Copy', comment: 'Copy in icons tooltip title'},
      'CollapseAppTray': {id: 'CollapseAppTray', value: 'Collapse App Tray', comment: 'Collapse App Tray in icons tooltip title'},
      'Columns': {id: 'Columns', value: 'Columns', comment: 'Columns in icons tooltip title'},
      'Compose': {id: 'Compose', value: 'Compose', comment: 'Compose in icons tooltip title'},
      'Completed': {id: 'Completed', value: 'Completed', comment: 'Text For a Completed Status'},
      'Confirm': {id: 'Confirm', value: 'Confirm', comment: 'Confirm in icons tooltip title'},
      'Contains': {id: 'Contains', value: 'Contains', comment: 'Contains in icons for filtering'},
      'Cut': {id: 'Cut', value: 'Cut', comment: 'Cut in icons tooltip title'},
      'Date': {id: 'Date', value: 'Date', comment: 'Describes filtering by a date data type'},
      'Document': {id: 'Document', value: 'Document', comment: 'Document in icons tooltip title'},
      'Drilldown': {id: 'Drilldown', value: 'Drill down', comment: 'Drill by moving page flow into a record'},
      'Drillup': {id: 'Drillup', value: 'Drill Up', comment: 'Opposite of Drilldown, move back up to a larger set of records'},
      'Dropdown': {id: 'Dropdown', value: 'Dropdown', comment: 'Dropdown'},
      'DoesNotContain': {id: 'DoesNotContain', value: 'Does Not Contain', comment: 'Does Not Contain in icons for filtering'},
      'DoesNotEqual': {id: 'DoesNotEqual', value: 'Does Not Equal', comment: 'Does Not Equal in icons for filtering'},
      'Down': {id: 'Down', value: 'Down', comment: 'Down in icons tooltip title'},
      'Download': {id: 'Download', value: 'Download', comment: 'Download in icons tooltip title'},
      'Duplicate': {id: 'Duplicate', value: 'Duplicate', comment: 'Duplicate in icons tooltip title'},
      'EitherSelectedOrNotSelected': {id: 'EitherSelectedOrNotSelected', value: 'Either Selected Or NotSelected', comment: 'Either Selected Or NotSelected in icons for filtering'},
      'EnterComments': {id: 'EnterComments', value: 'Enter comments here...', comment: 'Placeholder text for a text input (comments)'},
      'Error': {id: 'Error', value: 'Error', comment: 'Title, Spoken Text describing fact an error has occured'},
      'EmailValidation': {id: 'EmailValidation', value: 'Email address not valid', comment: 'This the rule for email validation'},
      'Emerald': {id: 'Emerald', value: 'Emerald', comment: 'Color in our color pallette'},
      'ExpandAppTray': {id: 'ExpandAppTray', value: 'Expand App Tray', comment: 'ExpandAppTray in icons tooltip title'},
      'ExpandCollapse': {id: 'ExpandCollapse', value: 'Expand / Collapse', comment: 'Text to toggle a button in a container.'},
      'ExportAsSpreadsheet': {id: 'ExportAsSpreadsheet', value: 'Export as Spreadsheet', comment: 'Export as Spreadsheet in icons tooltip title'},
      'Edit': {id: 'Edit', value: 'Edit', comment: 'Edit in icons tooltip title'},
      'Equals': {id: 'Equals', value: 'Equals', comment: 'Equals in icons for filtering'},
      'ExitFullView': {id: 'ExitFullView', value: 'Exit Full View', comment: 'Exit Full View in icons tooltip title'},
      'Export': {id: 'Export', value: 'Export', comment: 'Export in icons tooltip title'},
      'FileUpload': {id: 'FileUpload', value: 'File Upload Press Enter to Browse for a file', comment: 'Screen Reader instructions'},
      'Filter': {id: 'Filter', value: 'Filter', comment: 'Filter in icons tooltip title'},
      'FirstPage': {id: 'FirstPage', value: 'First Page', comment: 'First Page in icons tooltip title'},
      'Folder': {id: 'Folder', value: 'Folder', comment: 'Folder in icons tooltip title'},
      'FullView': {id: 'FullView', value: 'Full View', comment: 'Full View in icons tooltip title'},
      'GoUp': {id: 'GoUp', value: 'Go Up', comment: 'Go Up in icons tooltip title'},
      'Graphite': {id: 'Graphite', value: 'Graphite', comment: 'Color in our color pallette'},
      'GreaterOrEquals': {id: 'GreaterOrEquals', value: 'Greater Or Equals', comment: 'Greater Or Equals in icons for filtering'},
      'GreaterThan': {id: 'GreaterThan', value: 'Greater Than', comment: 'Greater Than in icons for filtering'},
      'Grid': {id: 'Grid', value: 'Grid', comment: 'Grid in icons tooltip title'},
      'Hours': {id: 'Hours', value: 'Hours', comment: 'the hour portion of a time'},
      'HeadingThree': {id: 'HeadingThree', value: 'Heading Three', comment: 'Heading Three in icons tooltip title'},
      'HeadingFour': {id: 'HeadingFour', value: 'Heading Four', comment: 'Heading Four in icons tooltip title'},
      'Home': {id: 'Home', value: 'Home', comment: 'Home in icons tooltip title'},
      'HtmlView': {id: 'HtmlView', value: 'Html View', comment: 'Html View in icons tooltip title'},
      'Import': {id: 'Import', value: 'Import', comment: 'Import in icons tooltip title'},
      'Info': {id: 'Info', value: 'Info', comment: 'Info in icons tooltip title'},
      'InsertAnchor': {id: 'InsertAnchor', value: 'Insert Anchor', comment: 'Insert Acnhor (link) in an editor'},
      'InsertImage': {id: 'InsertImage', value: 'Insert Image', comment: 'Insert Image in an editor'},
      'Italic': {id: 'Italic', value: 'Italic', comment: 'Make Text Italic'},
      'InvalidDate': {id: 'InvalidDate', value: 'Invalid Date', comment: 'validation message for wrong date format (short)'},
      'IsEmpty': {id: 'IsEmpty', value: 'Is Empty', comment: 'Is Empty in icons for filtering'},
      'IsNotEmpty': {id: 'IsNotEmpty', value: 'Is Not Empty', comment: 'Is Not Empty in icons for filtering'},
      'JustifyCenter': {id: 'JustifyCenter', value: 'Justify Center', comment: 'justify text to center in the editor'},
      'JustifyLeft': {id: 'JustifyLeft', value: 'Justify Left', comment: 'justify text to left in the editor'},
      'JustifyRight': {id: 'JustifyRight', value: 'Justify Right', comment: 'justify text to right in the editor'},
      'Keyword': {id: 'Keyword', value: 'Keyword', comment: 'Describes filtering by a keyword search'},
      'LastPage': {id: 'LastPage', value: 'Last Page', comment: 'Last Page in icons tooltip title'},
      'Left': {id: 'Left', value: 'Left', comment: 'Left in icons tooltip title'},
      'LeftAlign': {id: 'LeftAlign', value: 'Left Align', comment: 'Left Align in icons tooltip title'},
      'LeftTextAlign': {id: 'LeftTextAlign', value: 'Left Text Align', comment: 'Left Text Align in icons tooltip title'},
      'LessOrEquals': {id: 'LessOrEquals', value: 'Less Or Equals', comment: 'Less Or Equals in icons for filtering'},
      'LessThan': {id: 'LessThan', value: 'Less Than', comment: 'Less Than in icons for filtering'},
      'Link': {id: 'Link', value: 'Link', comment: 'Link in icons tooltip title'},
      'Load': {id: 'Load', value: 'Load', comment: 'Load in icons tooltip title'},
      'Loading': {id: 'Loading', value: 'Loading', comment: 'Text below spinning indicator to indicate loading'},
      'Locked': {id: 'Locked', value: 'Locked', comment: 'Locked in icons tooltip title'},
      'Mail': {id: 'Mail', value: 'Mail', comment: 'Mail in icons tooltip title'},
      'MapPin': {id: 'MapPin', value: 'Map Pin', comment: 'Map Pin in icons tooltip title'},
      'Maximize': {id: 'Maximize', value: 'Maximize', comment: 'Maximize in icons tooltip title'},
      'Medium': {id: 'Medium', value: 'Medium', comment: 'Describes a Medium Row Height in a grid/list'},
      'Menu': {id: 'Menu', value: 'Menu', comment: 'Menu in icons tooltip title'},
      'Minutes': {id: 'Minutes', value: 'Minutes', comment: 'the minutes portion of a time'},
      'Minimize': {id: 'Minimize', value: 'Minimize', comment: 'Minimize in icons tooltip title'},
      'Minus': {id: 'Minus', value: 'Minus', comment: 'Minus in icons tooltip title'},
      'More': {id: 'More', value: 'More...', comment: 'Text Indicating More Buttons or form content'},
      'MoreActions': {id: 'MoreActions', value: 'More Actions', comment: 'Text on the More Actions button indictating hidden functions'},
      'MultiselectWith': {id: 'MultiselectWith', value: '. Multiselect with ', comment: 'the minutes portion of a time'},
      'NewDocument': {id: 'NewDocument', value: 'New Document', comment: 'New Document in icons tooltip title'},
      'NewNextPage': {id: 'NewNextPage', value: 'New Next Page', comment: 'New Next Page in icons tooltip title'},
      'Next': {id: 'Next', value: 'Next', comment: 'Next in icons tooltip'},
      'NextMonth': {id: 'NextMonth', value: 'Next Month', comment: 'the label for the button that moves calendar to next/prev'},
      'NoResults': {id: 'NoResults', value: 'No Results', comment: 'Search Results Text'},
      'Notes': {id: 'Notes', value: 'Notes', comment: 'Notes in icons tooltip title'},
      'NotSelected': {id: 'NotSelected', value: 'Not Selected', comment: 'Not Selected in icons for filtering'},
      'NumberList': {id: 'NumberList', value: 'Number List', comment: 'Number List in icons tooltip title'},
      'OpenBackClose': {id: 'OpenBackClose', value: 'Open / Back / Close', comment: 'Open / Back / Close in icons tooltip title'},
      'OpenClose': {id: 'OpenClose', value: 'Open / Close', comment: 'Open / Close in icons tooltip title'},
      'OrderedList': {id: 'OrderedList', value: 'Ordered List', comment: 'Insert an Ordered list in the editor'},
      'Output': {id: 'Output', value: 'Output', comment: 'Output in icons tooltip title'},
      'Page': {id: 'Page', value: 'page ', comment: 'Text on the pager links'},
      'PageOn': {id: 'PageOn', value: 'You are currently on page ', comment: 'Text on the pager links'},
      'Paste': {id: 'Paste', value: 'Paste', comment: 'Paste in icons tooltip title'},
      'PasswordValidation': {id: 'PasswordValidation', value: '<div class="password-hint"><strong>Password must:</strong><ul><li>Be at least 10 characters long</li><li>Have at least one upper case character</li><li>Have at least one lower case character</li><li><strong>Contain one special character</strong></li><li>Not contain your username</li><li>Can not be a Prviously used password</li></ul></div>', comment: 'Password validation requirements'},
      'PasswordConfirmValidation': {id: 'PasswordConfirmValidation', value: 'Password must match', comment: 'Password Confirm validation'},
      'Peak': {id: 'Peak', value: 'Peak', comment: 'the max or peak value in a chart'},
      'PersonalizeColumns': {id: 'PersonalizeColumns', value: 'Personalize Columns', comment: 'Customize Columns in a Grid'},
      'Period': {id: 'Period', value: 'Period', comment: 'the am/pm portion of a time'},
      'PressDown': {id: 'PressDown', value: 'Press Down to select a date', comment: 'the audible label for hint about how to operate the date picker'},
      'Prev': {id: 'Prev', value: 'Prev', comment: 'Prev in icons tooltip title'},
      'Previous': {id: 'Previous', value: 'Previous', comment: 'Previous in icons tooltip title'},
      'PreviousMonth': {id: 'PreviousMonth', value: 'Previous Month', comment: 'the label for the button that moves calendar to next/prev'},
      'PreviousPage': {id: 'PreviousPage', value: 'Previous Page', comment: 'Previous Page in icons tooltip title'},
      'Print': {id: 'Print', value: 'Print', comment: 'Print in icons tooltip title'},
      'Quote': {id: 'Quote', value: 'Quote', comment: 'Quote in icons tooltip title'},
      'Redo': {id: 'Redo', value: 'Redo', comment: 'Redo in icons tooltip title'},
      'Refresh': {id: 'Refresh', value: 'Refresh', comment: 'Refresh in icons tooltip title'},
      'Required': {id: 'Required', value: 'Required', comment: 'indicates a form field is manditory'},
      'Reset': {id: 'Reset', value: 'Reset', comment: 'Reset in icons tooltip title'},
      'Results': {id: 'Results', value: 'Results', comment: 'As in showing N Results in a List'},
      'Right': {id: 'Right', value: 'Right', comment: 'Right in icons tooltip title'},
      'RightAlign': {id: 'RightAlign', value: 'Right Align', comment: 'Right Align in icons tooltip title'},
      'RightAlignText': {id: 'RightAlignText', value: 'Right Align Text', comment: 'Right Align Text in icons tooltip title'},
      'RightArrow': {id: 'RightArrow', value: 'Right Arrow', comment: 'Right Arrow in icons tooltip title'},
      'Roles': {id: 'Roles', value: 'Roles', comment: 'Roles in icons tooltip title'},
      'RowHeight': {id: 'RowHeight', value: 'Row Height', comment: 'Describes the Height for Rows in a Data Grid'},
      'Ruby': {id: 'Ruby', value: 'Ruby', comment: 'Color in our color pallette'},
      'Save': {id: 'Save', value: 'Save', comment: 'Save in icons tooltip title'},
      'SaveCurrentView': {id: 'SaveCurrentView', value: 'Save Current View', comment: 'Datagrids contain view sets. This menu option saves them'},
      'SavedViews': {id: 'SavedViews', value: 'Saved Views', comment: 'Label for a list of Views'},
      'Search': {id: 'Search', value: 'Search', comment: 'Search in icons tooltip title'},
      'SearchFolder': {id: 'SearchFolder', value: 'Search Folder', comment: 'Search Folder in icons tooltip title'},
      'SearchList': {id: 'SearchList', value: 'Search List', comment: 'Search List in icons tooltip title'},
      'Selected': {id: 'Selected', value: 'Selected', comment: 'text describing a selected object'},
      'Send': {id: 'Send', value: 'Send', comment: 'Send in icons tooltip title'},
      'SetTime': {id: 'SetTime', value: 'Set Time', comment: 'button text that inserts time when clicked'},
      'Settings': {id: 'Settings', value: 'Settings', comment: 'Settings in icons tooltip title'},
      'Short': {id: 'Short', value: 'Short', comment: 'Describes a Shorted Row Height in a grid/list'},
      'Slate': {id: 'Slate', value: 'Slate', comment: 'Color in our color pallette'},
      'SliderHandle': {id: 'SliderHandle', value: 'Handle for', comment: 'Description of the portion of a Slider control that is focusable and changes its value, followed in code by the name of the control'},
      'SliderMaximumHandle': {id: 'SliderMaximumHandle', value: 'Maximum range handle for', comment: 'Describes a maximum value handle in a Range (double slider), followed in code by the name of the control'},
      'SliderMinimumHandle': {id: 'SliderMinimumHandle', value: 'Minimum range handle for', comment: 'Describes a minimum value handle in a Range (double slider), followed in code by the name of the control'},
      'StrikeThrough': {id: 'StrikeThrough', value: 'Strike Through', comment: 'turn on and off strike through text in text editor (like word)'},
      'SortAtoZ': {id: 'SortAtoZ', value: 'Sort A to Z', comment: 'Sort A to Z in icons for filtering'},
      'SortZtoA': {id: 'SortZtoA', value: 'Sort Z to A', comment: 'Sort Z to A in icons for filtering'},
      'SortDown': {id: 'SortDown', value: 'Sort Down', comment: 'Sort Down in icons tooltip title'},
      'SortUp': {id: 'SortUp', value: 'Sort Up', comment: 'Sort Up in icons tooltip title'},
      'StarFilled': {id: 'StarFilled', value: 'Star Filled', comment: 'Star Filled in icons tooltip title'},
      'StarHalf': {id: 'StarHalf', value: 'Star Half', comment: 'Star Half in icons tooltip title'},
      'StarOutlined': {id: 'StarOutlined', value: 'Star Outlined', comment: 'Star Outlined in icons tooltip title'},
      'Subscript': {id: 'Subscript', value: 'Subscript', comment: 'turn on and off Subscript text in text editor (like word)'},
      'Superscript': {id: 'Superscript', value: 'Superscript', comment: 'turn on and off Superscript text in text editor (like word)'},
      'Tack': {id: 'Tack', value: 'Tack', comment: 'Tack in icons tooltip title'},
      'Tall': {id: 'Tall', value: 'Tall', comment: 'Describes a Taller Row Height in a grid/list'},
      'Timer': {id: 'Timer', value: 'Timer', comment: 'Timer in icons tooltip title'},
      'Today': {id: 'Today', value: 'Today', comment: 'refering to today on a calendar'},
      'ToggleBold': {id: 'ToggleBold', value: 'Toggle Bold Text', comment: 'turn on and off bold in text editor (like word)'},
      'ToggleH3': {id: 'ToggleH3', value: 'Toggle Heading 3', comment: 'turn on and off heading 3 text'},
      'ToggleH4': {id: 'ToggleH4', value: 'Toggle Heading 4', comment: 'turn on and off heading 4 text'},
      'ToggleItalic': {id: 'ToggleItalic', value: 'Toggle Italic Text', comment: 'turn on and off Italic in text editor (like word)'},
      'ToggleUnderline': {id: 'ToggleUnderline', value: 'Toggle Underline Text', comment: 'turn on and off Underline in text editor (like word)'},
      'Toolbar': {id: 'Toolbar', value: 'Toolbar', comment: 'describing the toolbar component'},
      'TopAlign': {id: 'TopAlign', value: 'Top Align', comment: 'Top Align in icons tooltip title'},
      'Total': {id: 'Total', value: 'Total', comment: 'mathematic total of a calculation'},
      'Trash': {id: 'Trash', value: 'Trash', comment: 'Trash in icons tooltip title'},
      'TreeCollapse': {id: 'TreeCollapse', value: 'Tree Collapse', comment: 'Tree Collapse in icons tooltip title'},
      'TreeExpand': {id: 'TreeExpand', value: 'Tree Expand', comment: 'Tree Expand in icons tooltip title'},
      'Turquoise': {id: 'Turquoise', value: 'Turquoise', comment: 'Color in our color pallette'},
      'Up': {id: 'Up', value: 'Up', comment: 'Up in icons tooltip title'},
      'Upload': {id: 'Upload', value: 'Upload', comment: 'Upload in icons tooltip title'},
      'UnavailableDate': {id: 'UnavailableDate', value: 'Unavailable Date', comment: 'Unavailable Date Text'},
      'Underline': {id: 'Underline', value: 'Underline', comment: 'Make text Underlined'},
      'Undo': {id: 'Undo', value: 'Undo', comment: 'Undo in icons tooltip title'},
      'Unlcked': {id: 'Unlcked', value: 'Unlcked', comment: 'Unlcked in icons tooltip title'},
      'UnorderedList': {id: 'UnorderedList', value: 'Unordered List', comment: 'Insert an Unordered list in the editor'},
      'Unsupported': {id: 'Unsupported', value: 'This content is not available because it uses features not supported in your current browser version.', comment: 'Suggesting browser upgrade for missing features.'},
      'Url': {id: 'Url', value: 'Url', comment: 'Url in icons tooltip title'},
      'UseArrow': {id: 'UseArrow', value: '. Use arrow keys to select.', comment: 'Instructional comments for screen readers'},
      'User': {id: 'User', value: 'User', comment: 'User in icons tooltip title'},
      'UserProfile': {id: 'UserProfile', value: 'User Profile', comment: 'User Profile in icons tooltip title'},
      'VerticalMiddleAlign': {id: 'VerticalMiddleAlign', value: 'Vertical Middle Align', comment: 'Vertical Middle Align in icons tooltip title'},
      'ViewSource': {id: 'ViewSource', value: 'View Source', comment: 'Toggle the source view in the editor'},
      'ViewVisual': {id: 'ViewVisual', value: 'View Visual', comment: 'Toggle the visual view in the editor'}
    }
  });
}));
