(function (factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module
    define('cultures/lv-LV', ['jquery'], factory);
    factory();
  } else if (typeof exports === 'object') {
    // Node/CommonJS
    module.exports = factory(require('jquery'));
  } else {
    // Browser globals
    factory(jQuery);
  }
}(function () {

  if (!Locale) {
    return;
  }

  //Get Latest from http://www.unicode.org/Public/cldr/25/
  Locale.addCulture('lv-LV', {
    //layout/language
    language: 'lv',
    englishName: 'Latvian (Latvia)',
    nativeName: 'latviešu (Latvija)',
    //layout/orientation/@characters
    direction: 'left-to-right',
    //ca-gregorian
    calendars: [{
      name: 'gregorian',
      //ca-gregorian/main/dates/calendars/gregorian/dateFormats/
      dateFormat: {'separator': '.', //Infered
                   'timeSeparator': ':',
                   'short': 'dd.MM.yyyy', //use four digit year
                   'medium': 'y. gada d. MMM',
                   'long': 'y. gada d. MMMM',
                   'full': 'EEEE, y. gada d. MMMM',
                   'month': 'd. MMMM',
                   'year': 'yyyy. MMMM',
                   'timestamp': 'HH:mm:ss',
                   'datetime': 'dd.MM.yyyy HH:mm'}, //Infered short + short gregorian/dateTimeFormats
      //ca-gregorian/main/dates/calendars/gregorian/days/format/short or abbreviated (2 digit)
      days: {
         wide: ['svētdiena', 'pirmdiena', 'otrdiena', 'trešdiena', 'ceturtdiena', 'piektdiena', 'sestdiena'],
         abbreviated: ['Sv', 'Pr', 'Ot', 'Tr', 'Ce', 'Pk', 'Se'],
         narrow: ['S', 'P', 'O', 'T', 'C', 'P', 'S']
      },
      //ca-gregorian/main/dates/calendars/gregorian/months/format/wide
      months: {
        wide: ['Janvāris', 'Februāris', 'Marts', 'Aprīlis', 'Maijs', 'Jūnijs', 'Jūlijs', 'Augusts', 'Septembris', 'Oktobris', 'Novembris', 'Decembris'],
        abbreviated: ['Janv.', 'Febr.', 'Marts', 'Apr.', 'Maijs', 'Jūn.', 'Jūl.', 'Aug.', 'Sept.', 'Okt.', 'Nov.', 'Dec.']
      },
      //ca-gregorian/main/dates/calendars/gregorian/timeFormats/short
      timeFormat: 'HH:mm',
      //ca-gregorian/main/dates/calendars/gregorian/dayPeriods/wide
      dayPeriods: ['priekšpusdienā', 'pēcpusdienā']
    }],
    //numbers/currencyFormats-numberSystem-latn/standard (Replace Sign http://www.currencysymbols.in ?)
    currencySign: 'Ls', //(Replace Sign http://www.currencysymbols.in ?)
    currencyFormat: '¤#,##0.00',
    //numbers/symbols-numberSystem-latn
    numbers: {
      percentSign: '%',
      percentFormat: '#,##0 %',
      minusSign: '-',
      decimal: ',',
      group: ' '
    },
    //Resx - Approved By Translation Team
    messages: {
      'AboutText': {id: 'AboutText', value: 'Autortiesības &copy; {0} Infor. Visas tiesības paturētas. Šeit norādītie vārdi un dizaina apzīmējumi ir Infor un/vai tā saistīto uzņēmumu un filiāļu preču zīmes un/vai reģistrētas preču zīmes. Visas tiesības paturētas. Visas citas šeit norādītās preču zīmes pieder to attiecīgajiem īpašniekiem.'},
      'Actions': {id: 'Actions', value: 'Darbības', comment: 'Tooltip text for the action button with additional in context actions'},
      'Add': {id: 'Add', value: 'Pievienot', comment: 'Add'},
      'AdvancedFilter': {id: 'AdvancedFilter', value: 'Izveidot detalizētu filtrēšanu', comment: 'In a data grid active an advanced filtering feature'},
      'Alert': {id: 'Alert', value: 'Brīdinājums', comment: 'Alert'},
      'AllResults': {id: 'AllResults', value: 'Visi rezultāti', comment: 'Search Results Text'},
      'AligntoBottom': {id: 'AligntoBottom', value: 'Līdzināt pie apakšmalas', comment: 'Align to Bottom tooltip'},
      'AlignCenterHorizontally': {id: 'AlignCenterHorizontally', value: 'Horizontāli līdzināt pie centra', comment: 'Align Center Horizontally tooltip'},
      'Amber': {id: 'Amber', value: 'Dzintara dzeltena', comment: 'Color in our color pallette'},
      'Amethyst': {id: 'Amethyst', value: 'Ametists', comment: 'Color in our color pallette'},
      'Apply': {id: 'Apply', value: 'Lietot', comment: 'Text in a button to apply an action'},
      'Attach': {id: 'Attach', value: 'Pievienot', comment: 'Attach'},
      'Azure': {id: 'Azure', value: 'Gaiši debeszila', comment: 'Color in our color pallette'},
      'Between': {id: 'Between', value: 'Starp', comment: 'Between in icons for filtering'},
      'Blockquote': {id: 'Blockquote', value: 'Citāta bloks', comment: 'insert a block quote in the editor'},
      'Bold': {id: 'Bold', value: 'Treknraksts', comment: 'Make text Bold'},
      'Bookmarked': {id: 'Bookmarked', value: 'Pievienots grāmatzīmēm', comment: 'Bookmark filled'},
      'BookmarkThis': {id: 'BookmarkThis', value: 'Pievienot šo grāmatzīmēm', comment: 'Bookmark outlined'},
      'Breadcrumb': {id: 'Breadcrumb', value: 'Atpakaļceļš', comment: 'Text describing the Breadcrumb'},
      'BulletedList': {id: 'BulletedList', value: 'Saraksts ar aizzīmēm', comment: 'Bulleted List tooltip'},
      'Calendar': {id: 'Calendar', value: 'Kalendārs', comment: 'Inline Text for the title of the Calendar control'},
      'Camera': {id: 'Camera', value: 'Kamera', comment: 'Camera tooltip'},
      'Cancel': {id: 'Cancel', value: 'Atcelt', comment: 'Cancel tooltip'},
      'CapsLockOn': {id: 'CapsLockOn', value: 'Ieslēgt burtslēgu', comment: 'Caps Lock On message'},
      'Cart': {id: 'Cart', value: 'Grozs', comment: 'Cart tooltip'},
      'CenterText': {id: 'CenterText', value: 'Centrs', comment: 'An Icon Tooltip'},
      'CharactersLeft': {id: 'CharactersLeft', value: 'Atlikušas rakstzīmes {0}', comment: 'indicator showing how many more characters you can type.'},
      'CharactersMax': {id: 'CharactersMax', value: 'Maksimālais rakstzīmju skaits no ', comment: 'indicator showing how many max characters you can type.'},
      'ChangeSelection': {id: 'ChangeSelection', value: '. Izmantojiet bulttaustiņus, lai mainītu atlasi.', comment: 'Audible Text for drop down list help'},
      'Checkbox': {id: 'Checkbox', value: 'Izvēles rūtiņa', comment: 'Checkbox tooltip'},
      'Checked': {id: 'Checked', value: 'Atzīmēts', comment: 'Checked tooltip'},
      'Clear': {id: 'Clear', value: 'Nodzēst', comment: 'Tooltip for a Clear Action'},
      'Clock': {id: 'Clock', value: 'Pulkstenis', comment: 'Clock tooltip'},
      'Close': {id: 'Close', value: 'Aizvērt', comment: 'Tooltip for a Close Button Action'},
      'Copy': {id: 'Copy', value: 'Kopēt', comment: 'Copy tooltip'},
      'Collapse': {id: 'Collapse', value: 'Sakļaut', comment: 'Collapse / close a tree/submenu'},
      'CollapseAppTray': {id: 'CollapseAppTray', value: 'Sakļaut aplikāciju pamatvirsmu', comment: 'Collapse App Tray tooltip'},
      'Columns': {id: 'Columns', value: 'Kolonnas', comment: 'Columns tooltip'},
      'Compose': {id: 'Compose', value: 'Ziņojuma sastādīšana', comment: 'Compose tooltip'},
      'Completed': {id: 'Completed', value: 'Pabeigts', comment: 'Text For a Completed Status'},
      'Confirm': {id: 'Confirm', value: 'Apstiprināt', comment: 'Confirm tooltip'},
      'Contains': {id: 'Contains', value: 'Satur', comment: 'Contains in icons for filtering'},
      'Cut': {id: 'Cut', value: 'Izgriezt', comment: 'Cut tooltip'},
      'Date': {id: 'Date', value: 'Datums', comment: 'Describes filtering by a date data type'},
      'Delete': {id: 'Delete', value: 'Dzēst', comment: 'Delete Toolbar Action Tooltip'},
      'DistributeHoriz': {id: 'DistributeHoriz', value: 'Izkliedēt horizontāli', comment: 'Icon button tooltip for action that distributes elements across Horizontally'},
      'Document': {id: 'Document', value: 'Dokuments', comment: 'Document tooltip'},
      'Drilldown': {id: 'Drilldown', value: 'Rādīt detalizēti', comment: 'Drill by moving page flow into a record'},
      'Drillup': {id: 'Drillup', value: 'Rādīt vispārīgi', comment: 'Opposite of Drilldown, move back up to a larger set of records'},
      'Dropdown': {id: 'Dropdown', value: 'Nolaižams', comment: 'Dropdown'},
      'DoesNotContain': {id: 'DoesNotContain', value: 'Neietver', comment: 'Does Not Contain in icons for filtering'},
      'DoesNotEqual': {id: 'DoesNotEqual', value: 'Nav vienāds', comment: 'Does Not Equal in icons for filtering'},
      'Down': {id: 'Down', value: 'Uz leju', comment: 'Down tooltip'},
      'Download': {id: 'Download', value: 'Lejupielādēt', comment: 'Download tooltip'},
      'Duplicate': {id: 'Duplicate', value: 'Dublicēt', comment: 'Duplicate tooltip'},
      'EitherSelectedOrNotSelected': {id: 'EitherSelectedOrNotSelected', value: 'Atlasīts vai nav atlasīts', comment: 'Either Selected Or NotSelected in icons for filtering'},
      'EnterComments': {id: 'EnterComments', value: 'Ievadiet komentārus šeit...', comment: 'Placeholder text for a text input (comments)'},
      'Error': {id: 'Error', value: 'Kļūda', comment: 'Title, Spoken Text describing fact an error has occured'},
      'EmailValidation': {id: 'EmailValidation', value: 'E-pasta adrese nav derīga', comment: 'This the rule for email validation'},
      'Emerald': {id: 'Emerald', value: 'Smaragdzaļa', comment: 'Color in our color pallette'},
      'Expand': {id: 'Expand', value: 'Izvērst', comment: 'Expand open a tree/submenu'},
      'ExpandAppTray': {id: 'ExpandAppTray', value: 'Izvērst aplikāciju pamatvirsmu', comment: 'ExpandAppTray tooltip'},
      'ExpandCollapse': {id: 'ExpandCollapse', value: 'Izvērst / sakļaut', comment: 'Text to toggle a button in a container.'},
      'ExportAsSpreadsheet': {id: 'ExportAsSpreadsheet', value: 'Eksportēt uz izklājlapu', comment: 'Export as Spreadsheet tooltip'},
      'Edit': {id: 'Edit', value: 'Rediģēt', comment: 'Edit tooltip'},
      'Equals': {id: 'Equals', value: 'Vienāds', comment: 'Equals in icons for filtering'},
      'ExitFullView': {id: 'ExitFullView', value: 'Iziet no pilna skata režīma', comment: 'Exit Full View tooltip'},
      'Export': {id: 'Export', value: 'Eksportēt', comment: 'Export tooltip'},
      'FileUpload': {id: 'FileUpload', value: 'Faila augšupielāde. Nospiediet taustiņu Ievadīt, lai meklētu failu', comment: 'Screen Reader instructions'},
      'Filter': {id: 'Filter', value: 'Filtrēt', comment: 'Filter tooltip'},
      'FirstPage': {id: 'FirstPage', value: 'Pirmā lappuse', comment: 'First Page tooltip'},
      'Folder': {id: 'Folder', value: 'Mape', comment: 'Folder tooltip'},
      'FullView': {id: 'FullView', value: 'Pilns skats', comment: 'Full View tooltip'},
      'GoForward': {id: 'GoForward', value: 'Uz priekšu', comment: 'Move Page / object this direction'},
      'GoBack': {id: 'GoBack', value: 'Atgriezties', comment: 'Move Page / object this directionp'},
      'GoDown': {id: 'GoDown', value: 'Uz leju', comment: 'Move Page / object this directionp'},
      'GoUp': {id: 'GoUp', value: 'Uz augšu', comment: 'Move Page / object this direction'},
      'Graphite': {id: 'Graphite', value: 'Grafīts', comment: 'Color in our color pallette'},
      'GreaterOrEquals': {id: 'GreaterOrEquals', value: 'Lielāks vai vienāds', comment: 'Greater Or Equals in icons for filtering'},
      'GreaterThan': {id: 'GreaterThan', value: 'Lielāks nekā', comment: 'Greater Than in icons for filtering'},
      'Grid': {id: 'Grid', value: 'Režģis', comment: 'Grid tooltip'},
      'Hours': {id: 'Hours', value: 'Stundas', comment: 'the hour portion of a time'},
      'HeadingThree': {id: 'HeadingThree', value: 'Trešais virsraksts', comment: 'Heading Three tooltip'},
      'HeadingFour': {id: 'HeadingFour', value: 'Ceturtais virsraksts', comment: 'Heading Four tooltip'},
      'Highest': {id: 'Highest', value: 'Visaugstākais', comment: 'Highest Four tooltip'},
      'Home': {id: 'Home', value: 'Sākums', comment: 'Home tooltip'},
      'HtmlView': {id: 'HtmlView', value: 'HTML skats', comment: 'Html View tooltip'},
      'Import': {id: 'Import', value: 'Importēt', comment: 'Import tooltip'},
      'Info': {id: 'Info', value: 'Informācija', comment: 'Info tooltip'},
      'InsertAnchor': {id: 'InsertAnchor', value: 'Ievietot hipersaiti', comment: 'Insert Acnhor (link) in an editor'},
      'InsertImage': {id: 'InsertImage', value: 'Ievietot attēlu', comment: 'Insert Image in an editor'},
      'Italic': {id: 'Italic', value: 'Slīpraksts', comment: 'Make Text Italic'},
      'InvalidDate': {id: 'InvalidDate', value: 'Nederīgs datums', comment: 'validation message for wrong date format (short)'},
      'Inventory': {id: 'Inventory', value: 'Inventārs', comment: 'Icon button tooltop for Inventory Action'},
      'IsEmpty': {id: 'IsEmpty', value: 'Ir tukšs', comment: 'Is Empty in icons for filtering'},
      'IsNotEmpty': {id: 'IsNotEmpty', value: 'Nav tukšs', comment: 'Is Not Empty in icons for filtering'},
      'JustifyCenter': {id: 'JustifyCenter', value: 'Taisnot pa centu', comment: 'justify text to center in the editor'},
      'JustifyLeft': {id: 'JustifyLeft', value: 'Taisnot pa kreisi', comment: 'justify text to left in the editor'},
      'JustifyRight': {id: 'JustifyRight', value: 'Taisnot pa labi', comment: 'justify text to right in the editor'},
      'Keyword': {id: 'Keyword', value: 'Atslēgvārds', comment: 'Describes filtering by a keyword search'},
      'Launch': {id: 'Launch', value: 'Palaist', comment: 'Launch'},
      'LastPage': {id: 'LastPage', value: 'Pēdējā lapa', comment: 'Last Page tooltip'},
      'Left': {id: 'Left', value: 'Pa kreisi', comment: 'Left tooltip'},
      'LeftAlign': {id: 'LeftAlign', value: 'Līdzināt pa kreisi', comment: 'Left Align tooltip'},
      'LeftTextAlign': {id: 'LeftTextAlign', value: 'Līdzināt tekstu pa kreisi', comment: 'Left Text Align tooltip'},
      'LessOrEquals': {id: 'LessOrEquals', value: 'Mazāks vai vienāds', comment: 'Less Or Equals in icons for filtering'},
      'LessThan': {id: 'LessThan', value: 'Mazāks par', comment: 'Less Than in icons for filtering'},
      'Link': {id: 'Link', value: 'Saite', comment: 'Link - as in hyperlink - icon tooltop'},
      'Load': {id: 'Load', value: 'Ielādēt', comment: 'Load icon tooltip'},
      'Loading': {id: 'Loading', value: 'Ielādēšana', comment: 'Text below spinning indicator to indicate loading'},
      'Locked': {id: 'Locked', value: 'Bloķēts', comment: 'Locked tooltip'},
      'Lookup': {id: 'Lookup', value: 'Uzmeklēšana', comment: 'Lookup - As in looking up a record or value'},
      'Lowest': {id: 'Lowest', value: 'Viszemākais', comment: 'Lowest - As in Lowest value'},
      'Mail': {id: 'Mail', value: 'Pasts', comment: 'Mail tooltip'},
      'MapPin': {id: 'MapPin', value: 'Piespraust kartē', comment: 'Map Pin tooltip'},
      'Maximize': {id: 'Maximize', value: 'Maksimizēt', comment: 'Maximize a screen or dialog in the UI'},
      'Median': {id: 'Median', value: 'Mediāna', comment: 'Median in Mathematics'},
      'Medium': {id: 'Medium', value: 'Vidējs', comment: 'Describes a Medium sized Row Height in a grid/list'},
      'Menu': {id: 'Menu', value: 'Izvēlne', comment: 'Menu tooltip'},
      'MingleShare': {id: 'MingleShare', value: 'Koplietot ar Ming.le', comment: 'Share the contextual object/action in the mingle system'},
      'Minutes': {id: 'Minutes', value: 'Minūtes', comment: 'the minutes portion of a time'},
      'Minimize': {id: 'Minimize', value: 'Minimizēt', comment: 'Minimize tooltip'},
      'Minus': {id: 'Minus', value: 'Mīnus', comment: 'Minus tooltip'},
      'More': {id: 'More', value: 'Vairāk...', comment: 'Text Indicating More Buttons or form content'},
      'MoreActions': {id: 'MoreActions', value: 'Vairāk darbību', comment: 'Text on the More Actions button indictating hidden functions'},
      'MsgDirty': {id: 'MsgDirty', value: 'Modificēts', comment: 'for modified form fields'},
      'MultiselectWith': {id: 'MultiselectWith', value: '. Vairākatlasīt ar ', comment: 'the minutes portion of a time'},
      'NewDocument': {id: 'NewDocument', value: 'Jauns dokuments', comment: 'New Document tooltip'},
      'Next': {id: 'Next', value: 'Nākamais', comment: 'Next in icons tooltip'},
      'NextPage': {id: 'NextPage', value: 'Nākamā lapa', comment: 'Next on Pager'},
      'NextMonth': {id: 'NextMonth', value: 'Nākammēnes', comment: 'the label for the button that moves calendar to next/prev'},
      'NoResults': {id: 'NoResults', value: 'Nav rezultātu', comment: 'Search Results Text'},
      'Notes': {id: 'Notes', value: 'Piezīmes', comment: 'Notes icon tooltip'},
      'NotSelected': {id: 'NotSelected', value: 'Nav atlasīts', comment: 'Not Selected in icons for filtering'},
      'NumberList': {id: 'NumberList', value: 'Numurētais saraksts', comment: 'Number List tooltip'},
      'OpenBackClose': {id: 'OpenBackClose', value: 'Atvērt / atpakaļ / aizvērt', comment: 'Open / Back / Close tooltip'},
      'OpenClose': {id: 'OpenClose', value: 'Atvērt / aizvērt', comment: 'Open / Close tooltip'},
      'OrderedList': {id: 'OrderedList', value: 'Numurēts saraksts', comment: 'Insert an Ordered list in the editor'},
      'Page': {id: 'Page', value: 'lapa ', comment: 'Text on the pager links'},
      'PageOf': {id: 'PageOf', value: '{0}. lapa no {1}', comment: 'Pager Text Showing current and number of pages'},
      'PageOn': {id: 'PageOn', value: 'Pašlaik Jūs esat uz { }. lapas ', comment: 'Text on the pager links'},
      'Paste': {id: 'Paste', value: 'Ielīmēt', comment: 'Paste icon tooltip'},
      'PasswordValidation': {id: 'PasswordValidation', value: '<strong>Parolei jāsatur:</strong><br>vismaz 10 rakstzīmes;<br>vismaz vienu lielu rakstzīmi;<br>vismaz vienu mazu rakstzīmi;<br><strong>vienu speciālu rakstzīmi;</strong><br>nevar saturēt Jūsu lietotājvārdu;<br>nevar izmantot iepriekš lietoto paroli.<br>', comment: 'Password validation requirements'},
      'PasswordConfirmValidation': {id: 'PasswordConfirmValidation', value: 'Parolei jāsakrīt', comment: 'Password Confirm validation'},
      'Peak': {id: 'Peak', value: 'Maksimālais', comment: 'the max or peak value in a chart'},
      'PersonalizeColumns': {id: 'PersonalizeColumns', value: 'Personalizēt slejas', comment: 'Customize Columns in a Grid'},
      'Period': {id: 'Period', value: 'Periods', comment: 'the am/pm portion of a time'},
      'PressDown': {id: 'PressDown', value: 'Nospiediet lejupvērsto bultiņu, lai atlasītu datumu', comment: 'the audible label for Tooltip about how to operate the date picker'},
      'PressShiftF10': {id: 'PressShiftF10', value: 'Nospiediet Shift+F10, lai atvērtu kontekstizvēlni.', comment: 'the audible infor for screen readers on how to use a field with a popup menu'},
      'Previous': {id: 'Previous', value: 'Iepriekšējais', comment: 'Previous icon tooltip - moved to previous record'},
      'PreviousMonth': {id: 'PreviousMonth', value: 'Iepriekšējais mēnesis', comment: 'the label for the button that moves calendar to next/prev'},
      'PreviousPage': {id: 'PreviousPage', value: 'Iepriekšējā lapa', comment: 'Previous Page tooltip'},
      'Print': {id: 'Print', value: 'Drukāt', comment: 'Print tooltip'},
      'Range': {id: 'Range', value: 'Diapazons', comment: 'Range for tooltip'},
      'RecordsPerPage': {id: 'RecordsPerPage', value: '{0} ierakstu vienā lappusē', comment: 'Dropd own allows the user to select how many visible records {} shows select value.'},
      'Redo': {id: 'Redo', value: 'Atcelt atsaukšanu', comment: 'Redo tooltip'},
      'Refresh': {id: 'Refresh', value: 'Atsvaidzināt', comment: 'Refresh tooltip'},
      'Required': {id: 'Required', value: 'Nepieciešams', comment: 'indicates a form field is manditory'},
      'Reset': {id: 'Reset', value: 'Atiestatīt', comment: 'Reset tooltip'},
      'Results': {id: 'Results', value: 'Rezultāti', comment: 'As in showing N Results in a List'},
      'Right': {id: 'Right', value: 'Pa labi', comment: 'Right tooltip'},
      'RightAlign': {id: 'RightAlign', value: 'Līdzināt pa labi', comment: 'Right Align tooltip'},
      'RightAlignText': {id: 'RightAlignText', value: 'Līdzināt tekstu pa labi', comment: 'Right Align Text tooltip'},
      'Roles': {id: 'Roles', value: 'Lomas', comment: 'Roles tooltip'},
      'RowHeight': {id: 'RowHeight', value: 'Rindas augstums', comment: 'Describes the Height for Rows in a Data Grid'},
      'Ruby': {id: 'Ruby', value: 'Rubīna', comment: 'Color in our color pallette'},
      'Save': {id: 'Save', value: 'Saglabāt', comment: 'Save tooltip'},
      'SaveCurrentView': {id: 'SaveCurrentView', value: 'Saglabāt pašreizējo skatu', comment: 'Datagrids contain view sets. This menu option saves them'},
      'SavedViews': {id: 'SavedViews', value: 'Saglabātie skati', comment: 'Label for a list of Views'},
      'Search': {id: 'Search', value: 'Meklēt', comment: 'Search tooltip'},
      'SearchFolder': {id: 'SearchFolder', value: 'Meklēt mapē', comment: 'Search Folder tooltip'},
      'SearchList': {id: 'SearchList', value: 'Meklēt sarakstā', comment: 'Search List tooltip'},
      'Selected': {id: 'Selected', value: 'Atlasīts', comment: 'text describing a selected object'},
      'Send': {id: 'Send', value: 'Nosūtīt', comment: 'Send tooltip'},
      'SetTime': {id: 'SetTime', value: 'Iestatīt laiku', comment: 'button text that inserts time when clicked'},
      'Settings': {id: 'Settings', value: 'Iestatījumi', comment: 'Settings tooltip'},
      'Short': {id: 'Short', value: 'Īss', comment: 'Describes a Shorted Row Height in a grid/list'},
      'Slate': {id: 'Slate', value: 'Zilganpelēka', comment: 'Color in our color pallette'},
      'SliderHandle': {id: 'SliderHandle', value: '[name of the control] turis', comment: 'Description of the portion of a Slider control that is focusable and changes its value, followed in code by the name of the control'},
      'SliderMaximumHandle': {id: 'SliderMaximumHandle', value: '[name of the control] maksimālā diapazona turis', comment: 'Describes a maximum value handle in a Range (double slider), followed in code by the name of the control'},
      'SliderMinimumHandle': {id: 'SliderMinimumHandle', value: '[name of the control] minimālā diapazona turis', comment: 'Describes a minimum value handle in a Range (double slider), followed in code by the name of the control'},
      'SkipToMain': {id: 'SkipToMain', value: 'Pāriet uz galveno saturu', comment: 'Skip link in header, jumps when clicked on to main area'},
      'StrikeThrough': {id: 'StrikeThrough', value: 'Pārsvītrot', comment: 'turn on and off strike through text in text editor (like word)'},
      'SortAtoZ': {id: 'SortAtoZ', value: 'Kārtot no A līdz Z', comment: 'Sort A to Z in icons for filtering'},
      'SortZtoA': {id: 'SortZtoA', value: 'Kārtot no Z līdz A', comment: 'Sort Z to A in icons for filtering'},
      'SortDown': {id: 'SortDown', value: 'Kārtot uz leju', comment: 'Sort Down tooltip'},
      'SortUp': {id: 'SortUp', value: 'Kārtot uz augšu', comment: 'Sort Up tooltip'},
      'StarFilled': {id: 'StarFilled', value: 'Aizpildītā zvaigznīte', comment: 'Star Filled tooltip'},
      'StarHalf': {id: 'StarHalf', value: 'Dalīji aizpildītā zvaigznīte', comment: 'Star Half tooltip'},
      'StarOutlined': {id: 'StarOutlined', value: 'Tukša zvaigznīte', comment: 'Star Outlined tooltip'},
      'Subscript': {id: 'Subscript', value: 'Apakšraksts', comment: 'Turn on and off Subscript text in text editor (like word)'},
      'Superscript': {id: 'Superscript', value: 'Augšraksts', comment: 'Turn on and off Superscript text in text editor (like word)'},
      'Tack': {id: 'Tack', value: 'Piespraust', comment: 'Tack tooltip'},
      'Tall': {id: 'Tall', value: 'Garš', comment: 'Describes a Taller Row Height in a grid/list'},
      'Timer': {id: 'Timer', value: 'Taimeris', comment: 'Timer tooltip'},
      'Today': {id: 'Today', value: 'Šodien', comment: 'refering to today on a calendar'},
      'ToggleBold': {id: 'ToggleBold', value: 'Pārslēgt tekstu treknrakstā', comment: 'turn on and off bold in text editor (like word)'},
      'ToggleH3': {id: 'ToggleH3', value: 'Pārslēgt virsrakstu H3', comment: 'turn on and off heading 3 text'},
      'ToggleH4': {id: 'ToggleH4', value: 'Pārslēgt virsrakstu H4', comment: 'turn on and off heading 4 text'},
      'ToggleItalic': {id: 'ToggleItalic', value: 'Pārslēgt tekstu slīprakstā', comment: 'turn on and off Italic in text editor (like word)'},
      'ToggleUnderline': {id: 'ToggleUnderline', value: 'Pārslēgt tekstu pasvītrojumā', comment: 'turn on and off Underline in text editor (like word)'},
      'Toolbar': {id: 'Toolbar', value: 'Rīkjosla', comment: 'describing the toolbar component'},
      'TopAlign': {id: 'TopAlign', value: 'Līdzināt pie augšas', comment: 'Top Align tooltip'},
      'Total': {id: 'Total', value: 'Kopā', comment: 'Mathematic total of a calculation'},
      'TreeCollapse': {id: 'TreeCollapse', value: 'Sakļaut koku', comment: 'Tree Collapse tooltip'},
      'TreeExpand': {id: 'TreeExpand', value: 'Izvērst koku', comment: 'Tree Expand tooltip'},
      'Turquoise': {id: 'Turquoise', value: 'Tirkīzzila', comment: 'Color in our color pallette'},
      'Up': {id: 'Up', value: 'Uz augšu', comment: 'Up tooltip'},
      'Upload': {id: 'Upload', value: 'Augšupielādēt', comment: 'Upload tooltip'},
      'UnavailableDate': {id: 'UnavailableDate', value: 'Datums nav pieejams', comment: 'Unavailable Date Text'},
      'Underline': {id: 'Underline', value: 'Pasvītrot', comment: 'Make text Underlined'},
      'Undo': {id: 'Undo', value: 'Atsaukt', comment: 'Undo tooltip'},
      'Unlocked': {id: 'Unlocked', value: 'Atbloķēts', comment: 'Unlocked tooltip'},
      'UnorderedList': {id: 'UnorderedList', value: 'Saraksts ar aizzīmēm', comment: 'Insert an Unordered list in the editor'},
      'Unsupported': {id: 'Unsupported', value: 'Šis saturs nav pieejams, jo tas izmanto līdzekļus, kas netiek atbalstīti ar jūsu pašreizēju pārlūkprogrammas versiju.', comment: 'Suggesting browser upgrade for missing features.'},
      'Url': {id: 'Url', value: 'Vietrādis URL', comment: 'Url tooltip'},
      'UseArrow': {id: 'UseArrow', value: '. Izmantojiet bulttaustiņus, lai izvēlētos.', comment: 'Instructional comments for screen readers'},
      'UseEnter': {id: 'UseEnter', value: '. Izmantojiet taustiņu Ievadīt vai lejupvērsto bultiņu uzmeklēšanai.', comment: 'Instructional comments for screen readers'},
      'User': {id: 'User', value: 'Lietotājs', comment: 'User tooltip'},
      'UserProfile': {id: 'UserProfile', value: 'Lietotāja profils', comment: 'User Profile tooltip'},
      'VerticalMiddleAlign': {id: 'VerticalMiddleAlign', value: 'Vertikāli līdzināt pie centra', comment: 'Vertical Middle Align tooltip'},
      'ViewSource': {id: 'ViewSource', value: 'Skatīt avotu', comment: 'Toggle the source view in the editor'},
      'ViewVisual': {id: 'ViewVisual', value: 'Skatīt rezultātu', comment: 'Toggle the visual view in the editor'}
    }
  });
}));
