(function (factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module
    define('cultures/fr-FR', ['jquery'], factory);
    factory();
  } else if (typeof exports === 'object') {
    // Node/CommonJS
    module.exports = factory(require('jquery'));
  } else {
    // Browser globals
    factory(jQuery);
  }
}(function () {

  if (!Locale) {
    return;
  }

  //Get Latest from http://www.unicode.org/Public/cldr/25/
  Locale.addCulture('ps-PS', {
    //layout/language
    language: 'ps',
    englishName: 'Psuedo (Test)',
    nativeName: 'Psuedo (Test)',
    //layout/orientation/@characters
    direction: 'left-to-right',
    //ca-gregorian
    calendars: [{
      //ca-gregorian/main/dates/calendars/gregorian/dateFormats/
      dateFormat: {'separator': '/', //Infered
                   'timeSeparator': ':',
                   'short': 'dd/MM/yyyy', //use four digit year
                   'medium': 'd MMM yyyy',
                   'long': 'd MMMM yyyy',
                   'full': 'EEEE d MMMM yyyy',
                   'month': 'd MMMM',
                   'year': 'MMMM yyyy',
                   'timestamp': 'HH:mm:ss',
                   'datetime': 'dd/MM/yyyy HH:mm'}, //Infered short + short gregorian/dateTimeFormats
      //ca-gregorian/main/dates/calendars/gregorian/days/format/short or abbreviated (2 digit)
      days: {
         wide: ['dimanche', 'lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi'],
         abbreviated: ['di', 'lu', 'ma', 'me', 'je', 've', 'sa']
      },
      //ca-gregorian/main/dates/calendars/gregorian/months/format/wide
      months: {
        wide: ['janvier', 'février', 'mars', 'avril', 'mai', 'juin', 'juillet', 'août', 'septembre', 'octobre', 'novembre', 'décembre'],
        abbreviated: ['janv.', 'févr.', 'mars', 'avr.', 'mai', 'juin', 'juil.', 'août', 'sept.', 'oct.', 'nov.', 'déc.']
      },
      //ca-gregorian/main/dates/calendars/gregorian/timeFormats/short
      timeFormat: 'HH:mm',
      //ca-gregorian/main/dates/calendars/gregorian/dayPeriods/wide
      dayPeriods: ['AM', 'PM']
    }],
    //numbers/currencyFormats-numberSystem-latn/standard (Replace Sign http://www.currencysymbols.in ?)
    currencySign: '€', //(Replace Sign http://www.currencysymbols.in ?)
    currencyFormat: '#,##0.00 ¤',
    //numbers/symbols-numberSystem-latn
    numbers: {
      percentSign: '%',
      percentFormat: '#,##0 %',
      minusSign: '-',
      decimal: ',',
      group: ' '
    },
    //Resx - Approved By Translation Team
    messages: {
      'AboutText': {id: 'AboutText', value: '#Thgíírypőőč &copy; {0} Rőfñí. Llââ sťhgír déévrésér. Ehť drőw dñâ ñgíséd skrâm ťés hťrőf ñíéréh érâ skrâmédârť rő/dñâ déréťsígér skrâmédârť fő Rőfñí rő/dñâ sťí séťâílíffâ dñâ séírâídísbüüs. Llâ sťhgír dévrésér. Llâ réhťő skrâmédârť déťsíl ñíéréh érâ éhť yťrépőrp fő ríéhť évíťčépsér sréñwő$'},
      'Actions': {id: 'Actions', value: '#Sñőőííťčââ$', comment: 'Tooltip text for the action button with additional in context actions'},
      'Add': {id: 'Add', value: 'Ajouter', comment: 'Add'},
      'AdvancedFilter': {id: 'AdvancedFilter', value: '#EEťââérč Déčñâvdâ Réťlííf$', comment: 'In a data grid active an advanced filtering feature'},
      'Alert': {id: 'Alert', value: 'Alerte', comment: 'Alert'},
      'AllResults': {id: 'AllResults', value: '#Llââ Sťlüüséér Rőőf$', comment: 'Search Results Text'},
      'AligntoBottom': {id: 'AligntoBottom', value: '#Ngíílââ Mőőťťőb$', comment: 'Align to Bottom tooltip'},
      'AlignCenterHorizontally': {id: 'AlignCenterHorizontally', value: '#Lââťñőőzíírőh Ngílâ Rééťñéč$', comment: 'Align Center Horizontally tooltip'},
      'Amber': {id: 'Amber', value: '#Réébmââ$', comment: 'Color in our color pallette'},
      'Amethyst': {id: 'Amethyst', value: '#Tsyhťéémââ$', comment: 'Color in our color pallette'},
      'Attach': {id: 'Attach', value: '#Hčââťťâ$', comment: 'Attach'},
      'Azure': {id: 'Azure', value: '#EErüüzââ$', comment: 'Color in our color pallette'},
      'Between': {id: 'Between', value: 'Entre', comment: 'Between in icons for filtering'},
      'Blockquote': {id: 'Blockquote', value: '#Kčőőlb ééťőüüq$', comment: 'insert a block quote in the editor'},
      'Bold': {id: 'Bold', value: '#Dlőőb$', comment: 'Make text Bold'},
      'Bookmarked': {id: 'Bookmarked', value: '#Déékrââmkőőőb$', comment: 'Bookmark filled'},
      'BookmarkThis': {id: 'BookmarkThis', value: '#Krââmkőőőb sííhť$', comment: 'Bookmark outlined'},
      'Breadcrumb': {id: 'Breadcrumb', value: '#Bmüürčdââéérb$', comment: 'Text describing the Breadcrumb'},
      'BulletedList': {id: 'BulletedList', value: '#Dééťéllüüb ťsííl$', comment: 'Bulleted List tooltip'},
      'Calendar': {id: 'Calendar', value: '#Rââdñéélâč$', comment: 'Inline Text for the title of the Calendar control'},
      'Camera': {id: 'Camera', value: '#AAréémâč$', comment: 'Camera tooltip'},
      'Cancel': {id: 'Cancel', value: 'Annuler', comment: 'Cancel tooltip'},
      'CapsLockOn': {id: 'CapsLockOn', value: '#Spââč Kčőől Nő$', comment: 'Caps Lock On message'},
      'Cart': {id: 'Cart', value: '#Trââč$', comment: 'Cart tooltip'},
      'CenterText': {id: 'CenterText', value: 'Centre', comment: 'An Icon Tooltip'},
      'CharactersLeft': {id: 'CharactersLeft', value: '#Srééťčâârâhč ťfél$ ', comment: 'indicator showing how many more characters you can type.'},
      'CharactersMax': {id: 'CharactersMax', value: '#Rééťčâârâhč ťñüüőőč mümííxâm fő$ ', comment: 'indicator showing how many max characters you can type.'},
      'ChangeSelection': {id: 'ChangeSelection', value: '#. OOť éégñââhč éhť ñőííťčélés ésüü éhť wőrrâ syék.$', comment: 'Audible Text for drop down list help'},
      'Checkbox': {id: 'Checkbox', value: '#Xőőbkčééhč$', comment: 'Checkbox tooltip'},
      'Checked': {id: 'Checked', value: 'Coché(e)', comment: 'Checked tooltip'},
      'Clear': {id: 'Clear', value: 'Effacer', comment: 'Tooltip for a Clear Action'},
      'Clock': {id: 'Clock', value: '#Kčőőlč$', comment: 'Clock tooltip'},
      'Close': {id: 'Close', value: 'Fermer', comment: 'Tooltip for a Close Button Action'},
      'Copy': {id: 'Copy', value: 'Copier', comment: 'Copy tooltip'},
      'Collapse': {id: 'Collapse', value: '#EEspââllőőč$', comment: 'Collapse / close a tree/submenu'},
      'CollapseAppTray': {id: 'CollapseAppTray', value: '#EEspââllőőč Ppâ Yârť$', comment: 'Collapse App Tray tooltip'},
      'Columns': {id: 'Columns', value: 'Colonnes', comment: 'Columns tooltip'},
      'Compose': {id: 'Compose', value: '#EEsőőpmőč$', comment: 'Compose tooltip'},
      'Completed': {id: 'Completed', value: 'Terminé', comment: 'Text For a Completed Status'},
      'Confirm': {id: 'Confirm', value: '#Mríífñőőč$', comment: 'Confirm tooltip'},
      'Contains': {id: 'Contains', value: 'Contient', comment: 'Contains in icons for filtering'},
      'Cut': {id: 'Cut', value: 'Couper', comment: 'Cut tooltip'},
      'Date': {id: 'Date', value: 'Date', comment: 'Describes filtering by a date data type'},
      'Delete': {id: 'Delete', value: 'Supprimer', comment: 'Delete Toolbar Action Tooltip'},
      'DistributeHoriz': {id: 'DistributeHoriz', value: 'Répartir horizontalement', comment: 'Icon button tooltip for action that distributes elements across Horizontally'},
      'Document': {id: 'Document', value: 'Document', comment: 'Document tooltip'},
      'Drilldown': {id: 'Drilldown', value: '#Llíírd ñwőőd$', comment: 'Drill by moving page flow into a record'},
      'Drillup': {id: 'Drillup', value: '#Llíírd Püü$', comment: 'Opposite of Drilldown, move back up to a larger set of records'},
      'Dropdown': {id: 'Dropdown', value: 'Liste déroulante', comment: 'Dropdown'},
      'DoesNotContain': {id: 'DoesNotContain', value: 'Ne contient pas', comment: 'Does Not Contain in icons for filtering'},
      'DoesNotEqual': {id: 'DoesNotEqual', value: 'N\'est pas égal(e)', comment: 'Does Not Equal in icons for filtering'},
      'Down': {id: 'Down', value: 'Bas', comment: 'Down tooltip'},
      'Download': {id: 'Download', value: 'Télécharger', comment: 'Download tooltip'},
      'Duplicate': {id: 'Duplicate', value: 'Copier', comment: 'Duplicate tooltip'},
      'EitherSelectedOrNotSelected': {id: 'EitherSelectedOrNotSelected', value: '#Rééhťííé Déťčélés Rőő DéťCélésťőñ$', comment: 'Either Selected Or NotSelected in icons for filtering'},
      'EnterComments': {id: 'EnterComments', value: '#Rééťñé sťñémmőőč éréh...$', comment: 'Placeholder text for a text input (comments)'},
      'Error': {id: 'Error', value: 'Erreur', comment: 'Title, Spoken Text describing fact an error has occured'},
      'EmailValidation': {id: 'EmailValidation', value: '#Lííââméé ssérddâ ťőőñ dílâv$', comment: 'This the rule for email validation'},
      'Emerald': {id: 'Emerald', value: '#Dlââréémé$', comment: 'Color in our color pallette'},
      'Expand': {id: 'Expand', value: 'Développer', comment: 'Expand open a tree/submenu'},
      'ExpandAppTray': {id: 'ExpandAppTray', value: '#Dñââpxéé Ppâ Yârť$', comment: 'ExpandAppTray tooltip'},
      'ExpandCollapse': {id: 'ExpandCollapse', value: '#Dñââpxéé / Espâllőőč$', comment: 'Text to toggle a button in a container.'},
      'ExportAsSpreadsheet': {id: 'ExportAsSpreadsheet', value: '#Trőőpxéé sââ Tééhsdâérps$', comment: 'Export as Spreadsheet tooltip'},
      'Edit': {id: 'Edit', value: 'Modifier', comment: 'Edit tooltip'},
      'Equals': {id: 'Equals', value: 'Est égal(e)', comment: 'Equals in icons for filtering'},
      'ExitFullView': {id: 'ExitFullView', value: '#Tííxéé Llüüf Wéív$', comment: 'Exit Full View tooltip'},
      'Export': {id: 'Export', value: 'Exporter', comment: 'Export tooltip'},
      'FileUpload': {id: 'FileUpload', value: '#EElííf Dââőőlpüü Ssérp Réťñé őť Eswőrb rőf â élíf$', comment: 'Screen Reader instructions'},
      'Filter': {id: 'Filter', value: 'Filtrer', comment: 'Filter tooltip'},
      'FirstPage': {id: 'FirstPage', value: '#Tsrííf EEgââp$', comment: 'First Page tooltip'},
      'Folder': {id: 'Folder', value: 'Dossier', comment: 'Folder tooltip'},
      'FullView': {id: 'FullView', value: '#Llüüf Wééíív$', comment: 'Full View tooltip'},
      'GoForward': {id: 'GoForward', value: '#OOg Drââwrőf$', comment: 'Move Page / object this direction'},
      'GoBack': {id: 'GoBack', value: 'Précédent', comment: 'Move Page / object this directionp'},
      'GoDown': {id: 'GoDown', value: '#OOg Nwőd$', comment: 'Move Page / object this directionp'},
      'GoUp': {id: 'GoUp', value: '#OOg Püü$', comment: 'Move Page / object this direction'},
      'Graphite': {id: 'Graphite', value: '#EEťííhpâârg$', comment: 'Color in our color pallette'},
      'GreaterOrEquals': {id: 'GreaterOrEquals', value: '#Rééťââérg Rőő Slâüüqé$', comment: 'Greater Or Equals in icons for filtering'},
      'GreaterThan': {id: 'GreaterThan', value: 'Supérieur à', comment: 'Greater Than in icons for filtering'},
      'Grid': {id: 'Grid', value: '#Díírg$', comment: 'Grid tooltip'},
      'Hours': {id: 'Hours', value: 'Heures', comment: 'the hour portion of a time'},
      'HeadingThree': {id: 'HeadingThree', value: '#Gñíídââééh Eérhť$', comment: 'Heading Three tooltip'},
      'HeadingFour': {id: 'HeadingFour', value: '#Gñíídââééh Rüüőőf$', comment: 'Heading Four tooltip'},
      'Highest': {id: 'Highest', value: '#Tsééhgííh$', comment: 'Highest Four tooltip'},
      'Home': {id: 'Home', value: 'Accueil', comment: 'Home tooltip'},
      'HtmlView': {id: 'HtmlView', value: '#Lmťh Wééíív$', comment: 'Html View tooltip'},
      'Import': {id: 'Import', value: 'Importer', comment: 'Import tooltip'},
      'Info': {id: 'Info', value: '#OOfñíí$', comment: 'Info tooltip'},
      'InsertAnchor': {id: 'InsertAnchor', value: '#Tréésñíí Rőőhčñââ$', comment: 'Insert Acnhor (link) in an editor'},
      'InsertImage': {id: 'InsertImage', value: '#Tréésñíí Egââmí$', comment: 'Insert Image in an editor'},
      'Italic': {id: 'Italic', value: '#Cíílââťí$', comment: 'Make Text Italic'},
      'InvalidDate': {id: 'InvalidDate', value: '#Díílââvñí EEťâd$', comment: 'validation message for wrong date format (short)'},
      'Inventory': {id: 'Inventory', value: 'Stocks', comment: 'Icon button tooltop for Inventory Action'},
      'IsEmpty': {id: 'IsEmpty', value: 'Est vide', comment: 'Is Empty in icons for filtering'},
      'IsNotEmpty': {id: 'IsNotEmpty', value: 'N\'est pas vide', comment: 'Is Not Empty in icons for filtering'},
      'JustifyCenter': {id: 'JustifyCenter', value: '#Yfííťsüüj Rééťñéč$', comment: 'justify text to center in the editor'},
      'JustifyLeft': {id: 'JustifyLeft', value: '#Yfííťsüüj Tféél$', comment: 'justify text to left in the editor'},
      'JustifyRight': {id: 'JustifyRight', value: '#Yfííťsüüj Thgír$', comment: 'justify text to right in the editor'},
      'Keyword': {id: 'Keyword', value: '#Drőőwyéék$', comment: 'Describes filtering by a keyword search'},
      'Launch': {id: 'Launch', value: '#Hčñüüââl$', comment: 'Launch'},
      'LastPage': {id: 'LastPage', value: '#Tsââl EEgâp$', comment: 'Last Page tooltip'},
      'Left': {id: 'Left', value: 'Gauche', comment: 'Left tooltip'},
      'LeftAlign': {id: 'LeftAlign', value: '#Tféél Ngíílââ$', comment: 'Left Align tooltip'},
      'LeftTextAlign': {id: 'LeftTextAlign', value: '#Tféél Txéť Ngíílââ$', comment: 'Left Text Align tooltip'},
      'LessOrEquals': {id: 'LessOrEquals', value: '#Sséél Rőő Slââüüqé$', comment: 'Less Or Equals in icons for filtering'},
      'LessThan': {id: 'LessThan', value: 'Inférieur à', comment: 'Less Than in icons for filtering'},
      'Link': {id: 'Link', value: 'Lien', comment: 'Link - as in hyperlink - icon tooltop'},
      'Load': {id: 'Load', value: '#Dââőől$', comment: 'Load icon tooltip'},
      'Loading': {id: 'Loading', value: 'Chargement', comment: 'Text below spinning indicator to indicate loading'},
      'Locked': {id: 'Locked', value: '#Déékčőől$', comment: 'Locked tooltip'},
      'Lookup': {id: 'Lookup', value: '#Püükőőől$', comment: 'Lookup - As in looking up a record or value'},
      'Lowest': {id: 'Lowest', value: '#Tsééwőől$', comment: 'Lowest - As in Lowest value'},
      'Mail': {id: 'Mail', value: 'Courrier', comment: 'Mail tooltip'},
      'MapPin': {id: 'MapPin', value: '#Pââm Nííp$', comment: 'Map Pin tooltip'},
      'Maximize': {id: 'Maximize', value: 'Agrandir', comment: 'Maximize a screen or dialog in the UI'},
      'Median': {id: 'Median', value: '#Nââíídéém$', comment: 'Median in Mathematics'},
      'Medium': {id: 'Medium', value: '#Müüíídéém$', comment: 'Describes a Medium sized Row Height in a grid/list'},
      'Menu': {id: 'Menu', value: 'Menu', comment: 'Menu tooltip'},
      'MingleShare': {id: 'MingleShare', value: '#EErââhs hťííw El.gñím$', comment: 'Share the contextual object/action in the mingle system'},
      'Minutes': {id: 'Minutes', value: '#Sééťüüñíím$', comment: 'the minutes portion of a time'},
      'Minimize': {id: 'Minimize', value: 'Réduire', comment: 'Minimize tooltip'},
      'Minus': {id: 'Minus', value: '#Süüñíím$', comment: 'Minus tooltip'},
      'More': {id: 'More', value: 'Plus...', comment: 'Text Indicating More Buttons or form content'},
      'MoreActions': {id: 'MoreActions', value: '#EErőőm Sñőííťčââ$', comment: 'Text on the More Actions button indictating hidden functions'},
      'MultiselectWith': {id: 'MultiselectWith', value: '#. Tčéélésííťlüüm hťíw$ ', comment: 'the minutes portion of a time'},
      'NewDocument': {id: 'NewDocument', value: '#Wééñ Tñémüüčőőd$', comment: 'New Document tooltip'},
      'Next': {id: 'Next', value: 'Suivant', comment: 'Next in icons tooltip'},
      'NextMonth': {id: 'NextMonth', value: 'Mois suivant', comment: 'the label for the button that moves calendar to next/prev'},
      'NoResults': {id: 'NoResults', value: '#OOñ Sťlüüséér$', comment: 'Search Results Text'},
      'Notes': {id: 'Notes', value: 'Remarques', comment: 'Notes icon tooltip'},
      'NotSelected': {id: 'NotSelected', value: 'Pas sélectionné(e)', comment: 'Not Selected in icons for filtering'},
      'NumberList': {id: 'NumberList', value: '#Réébmüüñ Tsííl$', comment: 'Number List tooltip'},
      'OpenBackClose': {id: 'OpenBackClose', value: '#Néépőő / Kčââb / Esőlč$', comment: 'Open / Back / Close tooltip'},
      'OpenClose': {id: 'OpenClose', value: '#Néépőő / Esőlč$', comment: 'Open / Close tooltip'},
      'OrderedList': {id: 'OrderedList', value: '#Déérédrőő Tsííl$', comment: 'Insert an Ordered list in the editor'},
      'Page': {id: 'Page', value: '#éégââp$ ', comment: 'Text on the pager links'},
      'PageOf': {id: 'PageOf', value: '#EEgââp {0} főő {1}$', comment: 'Pager Text Showing current and number of pages'},
      'PageOn': {id: 'PageOn', value: '#UUőőy éérââ ylťñérrüč ñő égâp$ ', comment: 'Text on the pager links'},
      'Paste': {id: 'Paste', value: 'Coller', comment: 'Paste icon tooltip'},
      'PasswordValidation': {id: 'PasswordValidation', value: '#vííd< claass="passwoord-Tooltip"><strong>Password muust:</strong><ul><li>Bee ťâ ťsâél 10 sréťčârâhč long</li><li>Have ťâ ťsâél éñő réppü ésâč character</li><li>Have ťâ ťsâél éñő réwől ésâč character</li><li><strong>Contain éñő lâíčéps character</strong></li><li>Not ñíâťñőč rüőy username</li><li>Can ťőñ éb â Ylsüőívrp désü password</li></ul></div>$', comment: 'Password validation requirements'},
      'PasswordConfirmValidation': {id: 'PasswordConfirmValidation', value: '#Drőőwssââp ťsüüm hčťâm$', comment: 'Password Confirm validation'},
      'Peak': {id: 'Peak', value: '#Kââéép$', comment: 'the max or peak value in a chart'},
      'PersonalizeColumns': {id: 'PersonalizeColumns', value: '#EEzíílââñőősrép Sñmüülőč$', comment: 'Customize Columns in a Grid'},
      'Period': {id: 'Period', value: 'Période', comment: 'the am/pm portion of a time'},
      'PressDown': {id: 'PressDown', value: '#Sséérp Nwőőd őť ťčélés ââ éťâd$', comment: 'the audible label for Tooltip about how to operate the date picker'},
      'PressShiftF10': {id: 'PressShiftF10', value: '#Sséérp 01f+ťfIIhs őőť ñépő éhť ťxéťñőč üüñém.$', comment: 'the audible infor for screen readers on how to use a field with a popup menu'},
      'Previous': {id: 'Previous', value: 'Précédent', comment: 'Previous icon tooltip - moved to previous record'},
      'PreviousMonth': {id: 'PreviousMonth', value: '#Süüőőíívéérp Hťñőm$', comment: 'the label for the button that moves calendar to next/prev'},
      'PreviousPage': {id: 'PreviousPage', value: 'Page précédente', comment: 'Previous Page tooltip'},
      'Print': {id: 'Print', value: 'Imprimer', comment: 'Print tooltip'},
      'Range': {id: 'Range', value: '#EEgñââr$', comment: 'Range for tooltip'},
      'RecordsPerPage': {id: 'RecordsPerPage', value: '#{0} Sdrőőčéér rép égââp$', comment: 'Dropd own allows the user to select how many visible records {} shows select value.'},
      'Redo': {id: 'Redo', value: 'Rétablir', comment: 'Redo tooltip'},
      'Refresh': {id: 'Refresh', value: 'Actualiser', comment: 'Refresh tooltip'},
      'Required': {id: 'Required', value: 'Requis', comment: 'indicates a form field is manditory'},
      'Reset': {id: 'Reset', value: 'Réinitialiser', comment: 'Reset tooltip'},
      'Results': {id: 'Results', value: 'Résultats', comment: 'As in showing N Results in a List'},
      'Right': {id: 'Right', value: 'Droite', comment: 'Right tooltip'},
      'RightAlign': {id: 'RightAlign', value: '#Thgíír Ngílââ$', comment: 'Right Align tooltip'},
      'RightAlignText': {id: 'RightAlignText', value: '#Thgíír Ngílââ Txééť$', comment: 'Right Align Text tooltip'},
      'Roles': {id: 'Roles', value: '#Séélőőr$', comment: 'Roles tooltip'},
      'RowHeight': {id: 'RowHeight', value: '#Wőőr Thgííééh$', comment: 'Describes the Height for Rows in a Data Grid'},
      'Ruby': {id: 'Ruby', value: '#Ybüür$', comment: 'Color in our color pallette'},
      'Save': {id: 'Save', value: 'Enregistrer', comment: 'Save tooltip'},
      'SaveCurrentView': {id: 'SaveCurrentView', value: '#EEvââs Tñérrüüč Wéíív$', comment: 'Datagrids contain view sets. This menu option saves them'},
      'SavedViews': {id: 'SavedViews', value: '#Déévââs Swéíív$', comment: 'Label for a list of Views'},
      'Search': {id: 'Search', value: 'Rechercher', comment: 'Search tooltip'},
      'SearchFolder': {id: 'SearchFolder', value: '#Hčrââéés Rédlőőf$', comment: 'Search Folder tooltip'},
      'SearchList': {id: 'SearchList', value: '#Hčrââéés Tsííl$', comment: 'Search List tooltip'},
      'Selected': {id: 'Selected', value: '#Dééťčélés$', comment: 'text describing a selected object'},
      'Send': {id: 'Send', value: 'Envoyer', comment: 'Send tooltip'},
      'SetTime': {id: 'SetTime', value: '#Téés Emííť$', comment: 'button text that inserts time when clicked'},
      'Settings': {id: 'Settings', value: 'Paramètres', comment: 'Settings tooltip'},
      'Short': {id: 'Short', value: '#Trőőhs$', comment: 'Describes a Shorted Row Height in a grid/list'},
      'Slate': {id: 'Slate', value: '#EEťââls$', comment: 'Color in our color pallette'},
      'SliderHandle': {id: 'SliderHandle', value: '#EEldñââh rőőf$', comment: 'Description of the portion of a Slider control that is focusable and changes its value, followed in code by the name of the control'},
      'SliderMaximumHandle': {id: 'SliderMaximumHandle', value: '#Müümííxââm éégñâr éldñâh rőőf$', comment: 'Describes a maximum value handle in a Range (double slider), followed in code by the name of the control'},
      'SliderMinimumHandle': {id: 'SliderMinimumHandle', value: '#Müümííñím éégñââr éldñâh rőőf$', comment: 'Describes a minimum value handle in a Range (double slider), followed in code by the name of the control'},
      'SkipToMain': {id: 'SkipToMain', value: '#Pííks őőť Níââm Tñééťñőč$', comment: 'Skip link in header, jumps when clicked on to main area'},
      'StrikeThrough': {id: 'StrikeThrough', value: '#EEkíírťs Hgüüőőrhť$', comment: 'turn on and off strike through text in text editor (like word)'},
      'SortAtoZ': {id: 'SortAtoZ', value: '#Trőős AA őť Z$', comment: 'Sort A to Z in icons for filtering'},
      'SortZtoA': {id: 'SortZtoA', value: '#Trőős Z őť AA$', comment: 'Sort Z to A in icons for filtering'},
      'SortDown': {id: 'SortDown', value: '#Trőős Nwőd$', comment: 'Sort Down tooltip'},
      'SortUp': {id: 'SortUp', value: '#Trőős Püü$', comment: 'Sort Up tooltip'},
      'StarFilled': {id: 'StarFilled', value: '#Rââťs Dééllííf$', comment: 'Star Filled tooltip'},
      'StarHalf': {id: 'StarHalf', value: '#Rââťs Flâh$', comment: 'Star Half tooltip'},
      'StarOutlined': {id: 'StarOutlined', value: '#Rââťs Dééñíílťüüőő$', comment: 'Star Outlined tooltip'},
      'Subscript': {id: 'Subscript', value: '#Tpíírčsbüüs$', comment: 'Turn on and off Subscript text in text editor (like word)'},
      'Superscript': {id: 'Superscript', value: '#Tpíírčsréépüüs$', comment: 'Turn on and off Superscript text in text editor (like word)'},
      'Tack': {id: 'Tack', value: '#Kčââť$', comment: 'Tack tooltip'},
      'Tall': {id: 'Tall', value: '#Llââť$', comment: 'Describes a Taller Row Height in a grid/list'},
      'Timer': {id: 'Timer', value: '#Réémííť$', comment: 'Timer tooltip'},
      'Today': {id: 'Today', value: 'Aujourd\'hui', comment: 'refering to today on a calendar'},
      'ToggleBold': {id: 'ToggleBold', value: '#EElggőőť Dlőb Txéť$', comment: 'turn on and off bold in text editor (like word)'},
      'ToggleH3': {id: 'ToggleH3', value: '#EElggőőť Gñíídââéh 3$', comment: 'turn on and off heading 3 text'},
      'ToggleH4': {id: 'ToggleH4', value: '#EElggőőť Gñíídââéh 4$', comment: 'turn on and off heading 4 text'},
      'ToggleItalic': {id: 'ToggleItalic', value: '#EElggőőť Cíílââťí Txéť$', comment: 'turn on and off Italic in text editor (like word)'},
      'ToggleUnderline': {id: 'ToggleUnderline', value: '#EElggőőť Eñíílrédñüü Txéť$', comment: 'turn on and off Underline in text editor (like word)'},
      'Toolbar': {id: 'Toolbar', value: '#Rââblőőőť$', comment: 'describing the toolbar component'},
      'TopAlign': {id: 'TopAlign', value: '#Pőőť Ngíílââ$', comment: 'Top Align tooltip'},
      'Total': {id: 'Total', value: 'Total', comment: 'Mathematic total of a calculation'},
      'TreeCollapse': {id: 'TreeCollapse', value: '#EEspââllőőč Eérť$', comment: 'Tree Collapse tooltip'},
      'TreeExpand': {id: 'TreeExpand', value: '#Dñââpxéé Eérť$', comment: 'Tree Expand tooltip'},
      'Turquoise': {id: 'Turquoise', value: 'Turquoise', comment: 'Color in our color pallette'},
      'Up': {id: 'Up', value: 'Haut', comment: 'Up tooltip'},
      'Upload': {id: 'Upload', value: '#Dââőőlpüü$', comment: 'Upload tooltip'},
      'UnavailableDate': {id: 'UnavailableDate', value: '#EElbââlííâvâñüü Eťâd$', comment: 'Unavailable Date Text'},
      'Underline': {id: 'Underline', value: '#EEñíílrédñüü$', comment: 'Make text Underlined'},
      'Undo': {id: 'Undo', value: '#OOdñüü$', comment: 'Undo tooltip'},
      'Unlocked': {id: 'Unlocked', value: '#DñUnlocked', comment: 'Unlocked tooltip'},
      'UnorderedList': {id: 'UnorderedList', value: '#DñUnordered List', comment: 'Insert an Unordered list in the editor'},
      'Unsupported': {id: 'Unsupported', value: '#DñThis content is not available because it uses features not supported in your current browser version.', comment: 'Suggesting browser upgrade for missing features.'},
      'Url': {id: 'Url', value: 'Url', comment: 'Url tooltip'},
      'UseArrow': {id: 'UseArrow', value: '. Use arrow keys to select.', comment: 'Instructional comments for screen readers'},
      'User': {id: 'User', value: 'Utilisateur', comment: 'User tooltip'},
      'UserProfile': {id: 'UserProfile', value: '#DñUser Profile', comment: 'User Profile tooltip'},
      'VerticalMiddleAlign': {id: 'VerticalMiddleAlign', value: '#DñVertical Align Middle', comment: 'Vertical Middle Align tooltip'},
      'ViewSource': {id: 'ViewSource', value: '#DñView Source', comment: 'Toggle the source view in the editor'},
      'ViewVisual': {id: 'ViewVisual', value: '#DñView Visual', comment: 'Toggle the visual view in the editor'}
    }

  });
}));
