#!/usr/bin/env node

/**
 * This script is a command line wrapper for `css-min`, which will
 * minify the CSS generated by the IDS Enterprise build system.
 */

// -------------------------------------
// Requirements
// -------------------------------------
import cssmin from 'cssmin';
import _yargs from 'yargs';
import { hideBin } from 'yargs/helpers';

import logger from './logger.js';
import getFileContents from './build/get-file-contents.js';
import writeFile from './build/write-file.js';

const config = {
  // Minify css
  cssmin: {
    options: {
      roundingPrecision: -1
    },
    dist: {
      files: {
        'dist/css/theme-classic-contrast.min.css': ['dist/css/theme-classic-contrast.css'],
        'dist/css/theme-classic-dark.min.css': ['dist/css/theme-classic-dark.css'],
        'dist/css/theme-classic-light.min.css': ['dist/css/theme-classic-light.css'],
        'dist/css/theme-new-light.min.css': ['dist/css/theme-new-light.css'],
        'dist/css/theme-new-dark.min.css': ['dist/css/theme-new-dark.css'],
        'dist/css/theme-new-contrast.min.css': ['dist/css/theme-new-contrast.css'],
        'dist/css/theme-soho-contrast.min.css': ['dist/css/theme-soho-contrast.css'],
        'dist/css/theme-soho-dark.min.css': ['dist/css/theme-soho-dark.css'],
        'dist/css/theme-soho-light.min.css': ['dist/css/theme-soho-light.css'],
        'dist/css/theme-uplift-light.min.css': ['dist/css/theme-uplift-light.css'],
        'dist/css/theme-uplift-dark.min.css': ['dist/css/theme-uplift-dark.css'],
        'dist/css/theme-uplift-contrast.min.css': ['dist/css/theme-uplift-contrast.css'],
      }
    },
  }

};

const argv = _yargs(hideBin(process.argv)).argv;

// -------------------------------------
// Functions
// -------------------------------------

function minify(srcFilePath, targetFilePath) {
  const css = getFileContents(srcFilePath);
  const minified = cssmin(css);
  return writeFile(targetFilePath, minified).then((err) => {
    if (err) {
      logger('error', `Error minifying "${srcFilePath}": ${err}`);
      return;
    }
    // Only log if not in --verbose mode (file logger has more detailed results)
    if (!argv.verbose) {
      logger('success', `Successfully minified "${targetFilePath}"`);
    }
  });
}

function minifyCSS() {
  return new Promise((resolve, reject) => {
    if (!config.cssmin.dist || !config.cssmin.dist.files) {
      throw new Error('Need to have target CSS files passed in for minifier');
    }

    const files = Object.keys(config.cssmin.dist.files);
    const processes = [];

    files.forEach((targetFileName) => {
      const srcFileName = config.cssmin.dist.files[targetFileName][0];
      processes.push(minify(srcFileName, targetFileName));
    });

    // eslint-disable-next-line no-promise-executor-return
    return Promise.all(processes).then(() => {
      resolve();
    }).catch((e) => {
      reject(e);
    });
  });
}

// -------------------------------------
// Main
// -------------------------------------
minifyCSS();
